"""
knife_edge_beam_profiler.py
===========================

Measure the width (FWHM / 1-e^2 diameter) of a focused beam from a knife-edge
scan.

Physics
-------
In a knife-edge measurement, a sharp edge is translated across a focused beam
while a detector records the transmitted power at each step. For a Gaussian
beam the recorded edge response is an error-function (sigmoid) curve. Its
spatial derivative recovers the beam's intensity profile, which is Gaussian;
the Full Width at Half Maximum (FWHM) of that Gaussian is the beam diameter at
the scan plane.

    edge scan  ->  d/dx  ->  Gaussian profile  ->  FWHM  ->  beam diameter

This works for any wavelength (visible, IR, THz, ...); the technique is
wavelength-agnostic. A synthetic edge is generated by default so the script
runs with no data, or you can supply your own two-column CSV (position, signal).

Usage
-----
    python knife_edge_beam_profiler.py                 # synthetic demo
    python knife_edge_beam_profiler.py --csv scan.csv  # your own scan
    python knife_edge_beam_profiler.py --save out.png  # headless, save figure

Author: Sidharth Raj
License: MIT
"""

from __future__ import annotations
import argparse
import numpy as np
from scipy.optimize import curve_fit
from scipy.signal import savgol_filter
from scipy.special import erf


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------
def gaussian(x, amp, mu, sigma):
    """Gaussian: amp = height, mu = centre, sigma = standard deviation."""
    return amp * np.exp(-0.5 * ((x - mu) / sigma) ** 2)


def erf_edge(x, x0, w, low, high):
    """
    Ideal knife-edge response of a Gaussian beam (integrated Gaussian).
    x0 = edge centre, w = 1/e^2 half-width, low/high = signal floor/ceiling.
    """
    return low + 0.5 * (high - low) * (1 + erf(np.sqrt(2) * (x - x0) / w))


def find_fwhm(x, y):
    """Return (fwhm, left_index, right_index) of a single peak in y."""
    peak = int(np.argmax(y))
    half = y[peak] / 2.0
    left = np.where(y[:peak] <= half)[0][-1]
    right = np.where(y[peak:] <= half)[0][0] + peak
    return x[right] - x[left], left, right


# ---------------------------------------------------------------------------
# Synthetic data (used when no CSV is given)
# ---------------------------------------------------------------------------
def synthetic_scan(distance_mm=7.0, beam_fwhm_mm=1.2, n=350, noise=0.004, seed=0):
    """Generate a realistic noisy knife-edge scan for demonstration."""
    rng = np.random.default_rng(seed)
    x = np.linspace(0.0, distance_mm, n)
    sigma = beam_fwhm_mm / (2.0 * np.sqrt(2.0 * np.log(2.0)))
    w = 2.0 * sigma  # 1/e^2 half-width
    y = erf_edge(x, x0=distance_mm / 2.0, w=w, low=0.0, high=1.0)
    y = y + noise * rng.standard_normal(n)
    return x, y


# ---------------------------------------------------------------------------
# Core analysis
# ---------------------------------------------------------------------------
def beam_width_from_edge(x, y, smooth=False, window=25, poly=2):
    """
    Differentiate a knife-edge response, fit a Gaussian, and return the FWHM.

    Returns a dict with the fitted parameters, the FWHM (beam diameter), the
    equivalent 1/e^2 diameter, and arrays for plotting.
    """
    y_proc = savgol_filter(y, window, poly) if smooth else np.asarray(y, float)

    dx = x[1] - x[0]
    dydx = np.abs(np.gradient(y_proc, dx))
    # Drop the two boundary samples where np.gradient is one-sided and noisy.
    xc, dc = x[1:-1], dydx[1:-1]

    span = x.max() - x.min()
    p0 = [dc.max(), xc[np.argmax(dc)], span / 20.0]
    bounds = ([0.0, x.min(), span / 500.0], [np.inf, x.max(), span / 2.0])
    popt, _ = curve_fit(gaussian, xc, dc, p0=p0, bounds=bounds, maxfev=20000)
    amp, mu, sigma = popt
    sigma = abs(sigma)

    fwhm = 2.0 * np.sqrt(2.0 * np.log(2.0)) * sigma  # exact for a Gaussian
    d_1e2 = 4.0 * sigma                               # 1/e^2 diameter (D4-sigma)

    x_fit = np.linspace(x.min(), x.max(), len(x) * 2)
    y_fit = gaussian(x_fit, amp, mu, sigma)

    return {
        "amplitude": amp, "centre": mu, "sigma": sigma,
        "fwhm": fwhm, "diameter_1e2": d_1e2,
        "x_proc": x, "y_proc": y_proc, "dydx": dydx,
        "x_fit": x_fit, "y_fit": y_fit,
        "half_left": mu - fwhm / 2.0, "half_right": mu + fwhm / 2.0,
        "half_level": amp / 2.0,
    }


# ---------------------------------------------------------------------------
# I/O + plotting
# ---------------------------------------------------------------------------
def load_csv(path):
    data = np.loadtxt(path, delimiter=",", skiprows=1)
    return data[:, 0], data[:, 1]


def plot(res, ylabel="Detector signal (a.u.)", save=None):
    import matplotlib
    if save:
        matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))

    ax1.plot(res["x_proc"], res["y_proc"], lw=2)
    ax1.set_title("Knife-edge response")
    ax1.set_xlabel("Edge position (mm)"); ax1.set_ylabel(ylabel)

    ax2.plot(res["x_proc"], res["dydx"], "g", lw=1.5, label="dy/dx (measured)")
    ax2.plot(res["x_fit"], res["y_fit"], "b", lw=2, label="Gaussian fit")
    ax2.plot([res["half_left"], res["half_right"]],
             [res["half_level"], res["half_level"]], "r", lw=2)
    ax2.scatter([res["half_left"], res["half_right"]],
                [res["half_level"], res["half_level"]], color="r", zorder=5)
    ax2.set_title(f"Beam profile  |  FWHM = {res['fwhm']:.3f} mm")
    ax2.set_xlabel("Edge position (mm)"); ax2.set_ylabel("Intensity (a.u.)")
    ax2.legend()

    fig.tight_layout()
    if save:
        fig.savefig(save, dpi=130)
        print(f"[saved] {save}")
    else:
        plt.show()


def main():
    ap = argparse.ArgumentParser(description="Knife-edge beam-width calculator.")
    ap.add_argument("--csv", help="Two-column CSV: position(mm), signal. "
                                   "If omitted, a synthetic scan is used.")
    ap.add_argument("--distance", type=float, default=7.0,
                    help="Synthetic scan length in mm (default 7).")
    ap.add_argument("--beam-fwhm", type=float, default=1.2,
                    help="True beam FWHM for the synthetic scan (default 1.2 mm).")
    ap.add_argument("--noise", type=float, default=0.004,
                    help="Synthetic noise level (default 0.004).")
    ap.add_argument("--smooth", action="store_true",
                    help="Apply Savitzky-Golay smoothing before differentiation.")
    ap.add_argument("--save", help="Save the figure to this path instead of showing it.")
    args = ap.parse_args()

    if args.csv:
        x, y = load_csv(args.csv)
    else:
        x, y = synthetic_scan(args.distance, args.beam_fwhm, noise=args.noise)

    res = beam_width_from_edge(x, y, smooth=args.smooth)
    print(f"Beam FWHM        : {res['fwhm']:.4f} mm")
    print(f"1/e^2 diameter   : {res['diameter_1e2']:.4f} mm")
    print(f"Fitted centre    : {res['centre']:.4f} mm")
    print(f"Fitted sigma     : {res['sigma']:.4f} mm")
    plot(res, save=args.save)


if __name__ == "__main__":
    main()
